### PR TITLE
Fix/common types

### PR DESCRIPTION
**Pull request by kmpm**
Makes life easier by letting UAP share some more common types.

### CODE REVIEW

**Comment by platinummonkey** [comment]
👋 thanks! can you merge latest HEAD on `master`? Needed to fix the action targets 🤦 for CI to run

**Comment by kmpm** [comment]
Am I understanding this correct, I can't use branches when contributing, it has to be on my master?

**Comment by platinummonkey** [comment]
no, you're fine, I made a mistake on the targets section for the build workflow

**Comment by kmpm** [comment]
Exactly what do you want me to do then? There is nothing new from your master that I can merge.

**Comment by platinummonkey** [comment]
There is a small diff that included a fix to run CI for forked pull requests: https://github.com/unpoller/unpoller/commit/a855dd2e50c25d2a29feb79b88ed2a41894f16df

**Comment by platinummonkey** [comment]
https://github.com/unpoller/unifi/commit/4eed4087ab4e92ef049050b9414f80095ab45275 should fix it 🤦 sorry about that

**Review by platinummonkey — APPROVED** [review]
thanks! 🙇

**Pull request merged**
